config/routes.rb
Rails.application.routes.draw do
  root "marketing/static_pages#homepage"

  namespace :admin do
    root to: "dashboards#show"

    resources :enrollments, only: [:index, :create]
    resources :profiles, only: [:index, :show]

    namespace :development do
      root to: "dashboards#show"

      namespace :portunus do
        root to: "dashboards#show"

        resources :kek_rotations, only: [:create]
      end
    end

    namespace :finance do
      root to: "dashboards#show"

      resources :revenue_records, only: [:index], path: :revenue
      resources :billing_features, only: [:index, :create, :new, :edit, :update]
      resources :billing_products, only: [:index, :edit, :update]
      resources :stripe_syncs, only: [:create]
    end

    namespace :support do
      root to: "dashboards#show"

      resources :companies, only: [:index, :show, :update] do
        namespace :companies, path: "" do
          resource :deletion, only: [:create]
        end
      end

      resources :members, only: [:index, :show]
      resources :support_requests, only: [:index, :show, :update, :destroy] do
        resources :support_request_messages, only: [:create]
      end
    end
  end

  scope module: :authentication, path: :auth, as: :auth do
    # For confirming the account
    resources :confirmations, only: [:index, :new, :create]
    resource :mobile_authenticator, only: [:update]
    resources :password_confirmations, only: [:new, :create]
    resources(
      :password_resets,
      only: [:index, :new, :create, :edit, :update],
      path: "forgot-password"
    )
    resources :signins, only: [:new, :create]
    resources :signups, only: [:new, :create]
    resources(
      :two_factor_authentications,
      only: [:new, :create],
      path: "sources"
    )

    resources :two_factor_sessions, only: [:new, :create]

    resources :webauthn_credentials, only: [:destroy]
    resources :webauthn_credentials, format: :js, only: [:create]
  end

  # omniauth
  get "/auth/:provider/callback", to: "authentication/omniauth#create"

  namespace :ichnaea do
    resources :events, only: [:create]
  end

  # we need devise here so we can access the sign_in methods
  devise_for :members, only: []

  devise_scope :member do
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  namespace :marketing do
    resources :contact_us_requests, only: [:new, :create], path: "contact-us"

    namespace :remote, defaults: { format: :js } do
      resources :beta_requests, only: :create
    end

    resources :unsubscribes, only: [:new, :create, :index]
  end

  namespace :dashboard do
    root "home#show"

    scope module: :company, path: :company, as: :company do
      resources :pending_members, only: [:index], path: "pending"
    end

    # TODO: Check me for making sure this is set up and configured correctly
    resource :notification_settings, only: [:show, :update]

    namespace :onboarding do
      resources :calendars, only: [:index]
      resources :companies, only: [:update]
      resources :company_settings, only: [:index]
      resources :introductions, only: [:index], path: "introduction"
    end

    namespace :settings do
      root "root#show"

      resources :account_deletions, only: [:create]
      resources :billings, only: [:index], path: "billing"

      namespace :billing do
        resources :downgrades, only: [:create, :update]
        resources :prices, only: [:index, :create]
        resources :invoices, only: [:show]

        resources(
          :payment_intents,
          only: [:create, :show, :update],
          path: "payments"
        )
      end

      resources :companies, only: [:index, :update], path: "company"
      resource :data_and_privacy, only: [:show]
      resources :gdpr_exports, only: [:create]
      resources :pending_members, only: [:index, :update], path: "pending"

      resources(
        :billing_sources,
        only: [:new, :create, :destroy, :update],
        path: "sources"
      )
    end

    resources(
      :profiles,
      only: [:index, :show, :new, :create],
      path: "employees"
    )

    resources :support_requests, only: [:index, :create], path: "support"
  end

  namespace :resque_web do
    resource  :overview, only: [:show], controller: :overview
    resources :working, only: [:index]
    resources :queues, only: [:index,:show,:destroy], constraints: { id: /[^\/]+/ } do
      member do
        put "clear"
      end
    end
    resources :workers, only: [:index,:show], constraints: { id: /[^\/]+/ }
    resources :failures, only: [:show,:index,:destroy] do
      member do
        put "retry"
      end
      collection do
        put "retry_all"
        delete "destroy_all"
      end
    end

    get "/stats", to: "stats#index"
    get "/stats/resque", to: "stats#resque"
    get "/stats/redis", to: "stats#redis"
    get "/stats/keys", to: "stats#keys"
    get "/stats/keys/:id", to: "stats#keys", constraints: { id: /[^\/]+/ }, as: :keys_statistic

    root to: "overview#show"
  end

  scope module: :utilities, path: :utilities, as: :utilities do
    resource :session_timezone, only: [:create]
  end

  namespace :webhooks do
    post "/sync_subscriptions/:id", to: "sync_subscriptions#update"
    post "/stripe", to: "stripes#create"
  end

  get "/about-us", to: "marketing/static_pages#about_us"
  get "/homepage", to: "marketing/static_pages#homepage"
  get "/pricing", to: "marketing/static_pages#pricing"

  if !Rails.env.production?
    get "/styleguide", to: "development#styleguide"
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < AdminController
    layout "admin"

    def show
    end
  end
end

app/controllers/admin/development/dashboards_controller.rb
module Admin::Development
  class DashboardsController < AdminController
    layout "admin/development"

    def show
    end
  end
end

app/controllers/admin/development/portunus/dashboards_controller.rb
module Admin::Development::Portunus
  class DashboardsController < AdminController
    layout "admin/development"

    def show
      @dek_counts_by_master = ::Portunus::Queries::DekCountByMasterKey.
        get_counts
    end
  end
end

app/controllers/admin/finance/dashboards_controller.rb
module Admin::Finance
  class DashboardsController < AdminController
    layout "admin/finance"

    def show
      @todays_revenue = Billing::Calculators::TodaysRevenue.for(DateTime.now)
    end
  end
end

app/controllers/admin/support/dashboards_controller.rb
module Admin::Support
  class DashboardsController < AdminController
    layout "admin/support"

    def show
    end
  end
end

app/controllers/dashboard/company/pending_members_controller.rb
module Dashboard::Company
  class PendingMembersController < AuthenticatedController
    layout "billing"

    skip_before_action :ensure_active_profile
    skip_before_action :check_broken_connections!

    def index
    end
  end
end

app/controllers/dashboard/company/stats_controller.rb
module Dashboard::Company
  class StatsController < AuthenticatedController
    def index
    end
  end
end

app/controllers/dashboard/connections_controller.rb
module Dashboard
  class ConnectionsController < AuthenticatedController
    skip_before_action :check_broken_connections!

    def index
      @auth_credential_statuses = AuthCredentials::Finder.
        new(session_info).
        find_with_statuses
    end

    def destroy
      auth_credential = AuthCredential.find(params[:id])

      authorize([:dashboard, auth_credential])

      if ::AuthCredentials::Disconnect.for(auth_credential)
        redirect_to dashboard_connections_path
      else
        redirect_to dashboard_connections_path
      end
    end
  end
end

app/controllers/dashboard/home_controller.rb
module Dashboard
  class HomeController < AuthenticatedController
    def show
    end
  end
end

app/controllers/dashboard/onboarding/companies_controller.rb
module Dashboard
  module Onboarding
    class CompaniesController < AuthenticatedController
      layout "billing"

      def update
        session_info.company.update(company_params)

        redirect_to(dashboard_onboarding_calendars_path)
      end

      private

      def company_params
        params.require(:company).permit(:email_domain, :open_signups, :name)
      end
    end
  end
end

app/controllers/dashboard/onboarding/company_settings_controller.rb
module Dashboard
  module Onboarding
    class CompanySettingsController < AuthenticatedController
      layout "billing"

      def index
      end
    end
  end
end

app/controllers/dashboard/onboarding/introductions_controller.rb
module Dashboard
  module Onboarding
    class IntroductionsController < AuthenticatedController
      layout "billing"

      def index
      end
    end
  end
end

app/controllers/dashboard/settings/account_deletions_controller.rb
module Dashboard::Settings
  class AccountDeletionsController < AuthenticatedController
    def create
      sign_out(session_info.member)

      redirect_to(
        root_path,
        flash: {
          success: "Your account was disabled and scheduled for removal"
        }
      )
    end
  end
end

app/controllers/dashboard/settings/billing/downgrades_controller.rb
module Dashboard::Settings::Billing
  class DowngradesController < AuthenticatedController
    def create
      @current_plan = ::Billing::Subscription.find_by(
        active: true,
        ownerable: session_info.account,
        cancelled_at: nil
      )

      if @current_plan.blank?
        redirect_to dashboard_settings_billings_path and return
      end

      ::Billing::Downgrade.create!(downgrade_params.merge(
        billing_subscription_id: @current_plan.id
      ))

      @current_plan.update!(cancelled_at: DateTime.now)

      Stripe::Subscription.update(
        @current_plan.billing_external_id.external_id,
        { cancel_at_period_end: true }
      )

      # we need to do lots here

      redirect_to dashboard_settings_billings_path
    end

    def update
      @billing_downgrade = ::Billing::Downgrade.find(params[:id])

      # TODO: pundit
      if @billing_downgrade.billing_subscription.ownerable != session_info.account
        redirect_to root_path and return
      end

      @current_plan = ::Billing::Subscription.find_by(
        active: true,
        ownerable: session_info.account
      )

      @current_plan.update!(cancelled_at: nil)
      @billing_downgrade.update(deleted_at: DateTime.now)

      ::Stripe::Subscription.update(
        @current_plan.billing_external_id.external_id,
        { cancel_at_period_end: false }
      )

      redirect_to dashboard_settings_billings_path
    end

    private

    def downgrade_params
      params.
        require(:billing_downgrade).
        permit(:reason).
        merge({
          profile_id: session_info.profile.id,
          downgraded_at: DateTime.now
        })
    end
  end
end

app/controllers/dashboard/settings/billing/invoices_controller.rb
module Dashboard::Settings::Billing
  class InvoicesController < AuthenticatedController
    layout "billing"

    def show
      @invoice = ::Billing::Invoice.find_by!(number: params[:id])

      # TODO: Pundit auth
      if @invoice.invoiceable != session_info.account
        redirect_to root_path and return
      end

      @stripe_invoice = ::Stripe::Invoice.retrieve(
        @invoice.billing_external_id.external_id
      )
    end
  end
end

app/controllers/dashboard/settings/billing/prices_controller.rb
module Dashboard
  module Settings
    module Billing
      class PricesController < AuthenticatedController
        layout "art_pane/billing"

        def index
          @current_plan = ::Billing::Subscription.find_by(
            active: true,
            ownerable: session_info.account
          )

          if params[:product_id] == "free"
            if @current_plan.present? && @current_plan.cancelled_at.blank?
              render "downgrade" and return
            else
              redirect_to dashboard_settings_billings_path and return
            end
          else
            @prices = ::Billing::Price.where(
              billing_product_id: params[:product_id]
            )
          end
        end
      end
    end
  end
end

app/controllers/dashboard/settings/billing_sources_controller.rb
module Dashboard::Settings
  class BillingSourcesController < AuthenticatedController
    layout "art_pane/billing"

    def new
      @source = ::Billing::Source.new
    end

    def create
      @source = ::Billing::Source.new(source_params)

      if @source.save
        stripe_source_id = @source.billing_external_id.external_id
        customer = ::Billing::CustomerFinder.for(session_info)

        ::Stripe::Source.update(
          stripe_source_id,
          {
            owner: {
              email: session_info.profile.email,
              name: session_info.profile.full_name,
              address: {
                city: @source.billing_detail.address.city,
                country: @source.billing_detail.address.country_code,
                line1: @source.billing_detail.address.line_1,
                line2: @source.billing_detail.address.line_2,
                postal_code: @source.billing_detail.address.postalcode,
                state: @source.billing_detail.address.province
              }
            },
            metadata: {
              application_id: @source.id
            }
          },
        )

        Stripe::Customer.create_source(
          customer.billing_external_id.external_id,
          {
            source: @source.billing_external_id.external_id,
          }
        )
      end

      if @source.persisted?
        redirect_to dashboard_settings_billings_path
      else
        render :new
      end
    end

    def update
      # this action only lets someone promote to default
      @source = ::Billing::Source.
        where(sourceable: session_info.account).
        find(params[:id])

      subscription = ::Billing::Subscriptions::Finder.for(
        session_info.account
      )

      if subscription.present?
        ::Billing::Subscriptions::SetDefaultSource.for(
          session_info,
          @source
        )
      end

      @source.update(default: true)

      redirect_to dashboard_settings_billings_path
    end

    def destroy
      @source = ::Billing::Source.
        where(sourceable: session_info.account).
        find(params[:id])

      @source.update(deleted_at: DateTime.now)

      redirect_to dashboard_settings_billings_path
    end

    private

    def source_params
      params.
        require(:billing_source).
        permit(
          :default,
          :exp_year,
          :exp_month,
          :brand,
          :last_four,
          {
            billing_detail_attributes: [
              :entity_type,
              :entity_name,
              :tax_number,
              {
                address_attributes: [
                  :line_1,
                  :line_2,
                  :city,
                  :province,
                  :postalcode
                ]
              }
            ],
            billing_external_id_attributes: [:external_id]
          }
        ).
        to_h.
        deep_merge(
          sourceable: session_info.account,
          source_type: :card,
          created_by_id: session_info.profile.id,
          billing_detail_attributes: {
            detailable: session_info.account,
            address_attributes: {
              company_id: session_info.company.id
            }
          }
        )
    end
  end
end

app/controllers/dashboard/settings/billings_controller.rb
module Dashboard::Settings
  class BillingsController < AuthenticatedController
    layout "art_pane/billing"

    def index
      @current_plan = ::Billing::Subscription.find_by(
        active: true,
        ownerable: session_info.account
      )

      @plans = ::Billing::PlansWithPrices.collect

      @sources = ::Billing::Source.where(
        sourceable: session_info.account,
        deleted_at: nil
      ).order([:exp_year, :exp_month])

      @invoices = ::Billing::Invoice.where(
        invoiceable: session_info.account
      ).order(created_at: :desc)
    end
  end
end

app/controllers/dashboard/settings/companies_controller.rb
module Dashboard
  module Settings
    class CompaniesController < AuthenticatedController
      def index
      end

      def update
        session_info.company.update(company_params)

        redirect_to(
          dashboard_settings_root_path,
          flash: { success: "Your settings have been updated" }
        )
      end

      private

      def company_params
        params
          .require(:company)
          .permit(
            :email_domain,
            :name,
            :open_signups
          )
      end
    end
  end
end

app/views/dashboard/calendars/_calendar_list_item.html.erb
<div class="dashboard-calendars-calendar_list_item">
  <aside class="provider-image">
    <%= image_tag(
      Providers::ImagePaths::ICON[calendar.provider.to_sym]
    ) %>
  </aside>

  <section class="calendar-details">
    <div class="details">
      <div class="name">
        <h3><%= calendar.name %></h3>
      </div>

      <div class="last-sync"
           data-controller="dashboard--calendars--perform-sync">
        <small class="lastSyncDateTarget">
          <% if calendar.last_event_sync %>
            <%= l(calendar.last_event_sync) %>
          <% else %>
            Not yet synced
          <% end %>
        </small>
      </div>
    </div>

    <div class="meeting-room"
         data-url="<%= dashboard_remote_calendar_path(calendar, format: :json) %>"
         data-meeting-room="<%= calendar.meeting_room? %>"
         data-controller="dashboard--calendars--toggle-meeting-room">
      <%= ion_icon(
        "ios-home",
        title: "Is this a meeting room?",
        data: {
          action: "click->dashboard--calendars--toggle-meeting-room#toggle",
          toggle: "tooltip"
        }
      ) %>
    </div>

    <div class="metrics"
         data-url="<%= dashboard_remote_calendar_path(calendar, format: :json) %>"
         data-metrics-enabled="<%= calendar.analytics_enabled %>"
         data-controller="dashboard--calendars--enable-metrics">
       <%= ion_icon(
         "erlenmeyer-flask-bubbles",
          title: "Enable calendar metrics",
          data: {
            action: "click->dashboard--calendars--enable-metrics#toggle",
            toggle: "tooltip"
          }
       ) %>
    </div>

    <div class="sync-events"
         data-start-sync-url="<%= dashboard_remote_syncs_path %>"
         data-calendar-id="<%= calendar.id %>"
         data-refresh-url="<%= dashboard_remote_calendar_path(calendar, format: :json) %>"
         data-sync-in-progress="<%= calendar.sync_in_progress %>"
         data-controller="dashboard--calendars--perform-sync">
      <%= ion_icon(
        "loop",
        title: "Sync calendar",
        data: {
          action: "click->dashboard--calendars--perform-sync#startSync",
          toggle: "tooltip"
        }
      ) %>
    </div>

    <div class="disable"
         data-url="<%= dashboard_remote_calendar_path(calendar, format: :json) %>"
         data-sync-enabled="<%= calendar.sync_enabled %>"
         data-calendar-id="<%= calendar.id %>"
         data-controller="dashboard--calendars--enable-sync">
      <%= ion_icon(
        "power",
        title: "Enable calendar",
        data: {
          action: "click->dashboard--calendars--enable-sync#toggle",
          toggle: "tooltip"
        }
      ) %>
    </div>
  </section>
</div>

app/views/dashboard/calendars/_importing.html.erb
<div class="dashboard-calendars-importing">
  <div data-controller="dashboard--syncs--calendar-sync"
       data-start-sync="<%= start_sync %>"
       data-url="<%= dashboard_remote_syncs_path%>">

    <div class="sync-pane frame">
      <section>
        <aside>
          <%= image_tag("illustrations/calendars/online_calendar_purple.svg") %>
        </aside>

        <article>
          <h3>Manage your calendars</h3>
          The calendars we found for your providers are listed below. Read more
          about how to configure and optimize your calendars here. Don't see
          the calendar you want? Simply hit refresh below or manage your
          providers.


          <div class="buttons">
            <button class="button primary outline"
                    data-action="click->dashboard--syncs--calendar-sync#startSync">
              Refresh calendars
            </button>

            <%= link_to(
              "Manage connections",
              dashboard_connections_path,
              class: "button secondary outline"
            ) %>
          </div>

          <div class="in-progress hidden">
            <%= render partial: "components/spinner" %>
            <h5>Refreshing your calendars...</h5>
          </div>

          <div class="sync-error hidden">
            <small>
              Sorry, something went wrong on our end. There's
              nothing you can do but we have been notified and will reach out
              as soon as it's fixed.
            </small>
          </div>
        </article>
      </section>
    </div>
  </div>
</div>

app/views/dashboard/calendars/_index_list.html.erb
<div class="dashboard-calendars-index_list">
  <% calendars.each do |calendar| %>
    <%= render(
      partial: "calendar_list_item",
      locals: {
        calendar: calendar
      }
    ) %>
  <% end %>
</div>

app/views/dashboard/calendars/index.html.erb
<div class="dashboard-calendars-index">
  <%= render(
    partial: "dashboard/calendars/importing",
    locals: {
      start_sync: @calendars.blank?
    }
  ) %>

  <%= render(
    partial: "dashboard/calendars/index_list",
    locals: {
      calendars: @calendars
    }
  ) %>
</div>

app/views/dashboard/calendars/show.html.erb
<div class="dashboard-calendars-show">
  <%= @calendar.name %>
</div>